import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    fontFamily: "Helvetica",
  },
  section: {
    marginBottom: 20,
  },
  title: {
    fontSize: 14,
    marginBottom: 10,
    fontWeight: "bold",
  },
  subtitle: {
    fontSize: 12,
    marginBottom: 8,
    fontWeight: "bold",
  },
  text: {
    fontSize: 11,
    marginBottom: 5,
    lineHeight: 1.4,
  },
  header: {
    marginBottom: 20,
  },
});

export const EvaluationReport = ({ results, jobPost, candidateName }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>CANDIDATE EVALUATION REPORT</Text>
        <Text style={styles.text}>Candidate Name: {candidateName}</Text>
        <Text style={styles.text}>Date: {new Date().toLocaleDateString()}</Text>
        <Text style={styles.text}>
          Report Reference: EVA-{new Date().getTime().toString().slice(-6)}
        </Text>
      </View>

      {/* Executive Summary */}
      <View style={styles.section}>
        <Text style={styles.title}>1. EXECUTIVE SUMMARY</Text>
        <Text style={styles.text}>
          Overall Match Score: {results.ai_insights.match_scores.overall_match}%
        </Text>
        <Text style={styles.text}>
          Skills Match Score: {results.ai_insights.match_scores.skills_match}%
        </Text>
        <Text style={styles.text}>
          Qualification Status:{" "}
          {results.ai_insights.match_scores.qualified
            ? "Qualified"
            : "Not Qualified"}
        </Text>
      </View>

      {/* Key Findings */}
      <View style={styles.section}>
        <Text style={styles.title}>2. KEY FINDINGS</Text>
        {Object.entries(results.ai_insights.sections)
          .slice(0, 2)
          .map(([key, section], index) => (
            <View key={key} style={styles.section}>
              <Text style={styles.subtitle}>
                2.{index + 1}. {section.title}
              </Text>
              <Text style={styles.text}>{section.content}</Text>
            </View>
          ))}
      </View>

      {/* Detailed Analysis */}
      <View style={styles.section}>
        <Text style={styles.title}>4. DETAILED ANALYSIS</Text>
        {Object.entries(results.ai_insights.sections)
          .slice(2)
          .map(([key, section], index) => (
            <View key={key} style={styles.section}>
              <Text style={styles.subtitle}>
                4.{index + 1}. {section.title}
              </Text>
              <Text style={styles.text}>{section.content}</Text>
            </View>
          ))}
      </View>

      {/* Footer */}
      <View style={styles.section}>
        <Text style={styles.text}>Generated by HireFlow</Text>
        <Text style={styles.text}>Report ID: {new Date().getTime()}</Text>
        <Text style={styles.text}>
          Generated on: {new Date().toLocaleString()}
        </Text>
      </View>
    </Page>
  </Document>
);
